Add komabasai2021
hideo54/esolang-battle pull request #8
Opened 2021-11-20 14:17 UTC by kom-bu

Add komabasai2021.js.
Implement `generateInput` and `isValidAnswer`.
Other features are just copied from mayfes2020-day1.js.

2021-11-20 15:25 UTC, hideo54 commented
お疲れさまです。問題文や言語などが固まり次第そちらの方もよろしくお願いします。

2021-11-20 16:48 UTC, kom-bu commented
え、盤面の編集一度もやったことないな……できるかわかんないです

2021-11-21 05:43 UTC, hideo54 commented
![](https://pbs.twimg.com/media/DVFGfVzVoAA5NaH?format=jpg&name=900x900)

2021-11-22 10:58 UTC, hideo54 requested changes
お疲れさまです

2021-11-22 10:58 UTC, hideo54 commented on bin/migrate-contest.js
> +const contestIds = ['komabasai2021'];
実はこのファイルは変える必要ないんですよね〜 すいません! (戻しといてくれると嬉しい)

2021-11-22 10:58 UTC, hideo54 commented on public/js/contests/mayfes2018/app.jsx
> +		if (this.contestId === 'mayfes2020-day1', this.contestId === 'komabasai2021') {
[MUST] `,` ではなくて `||` ですね〜。そして`['mayfes2020-day1', 'komabasai2021'].includes(this.contestId)` と書くと楽できます。

2021-11-22 10:58 UTC, hideo54 commented on views/contest.pug
> -    if contest.id === '1'
これなんで記法を変えたんかわからんけどまあ信じますね

2021-11-22 11:12 UTC, kom-bu commented on views/contest.pug
> -    if contest.id === '1'
え、全く身に覚えがない……（やば）

2021-11-22 11:12 UTC, kom-bu commented on views/contest.pug
> -    if contest.id === '1'
え、全く身に覚えがない……（やば）

2021-11-22 11:13 UTC, kom-bu commented on bin/migrate-contest.js
> +const contestIds = ['komabasai2021'];
もどしました！

2021-11-22 11:14 UTC, hideo54 commented on views/contest.pug
> -    if contest.id === '1'
じゃあ昆布くんの無意識を信じますね

2021-11-22 11:23 UTC, kom-bu commented on views/contest.pug
> -    if contest.id === '1'
まじで知らない構文です　lintか何か……？

2021-11-22 11:25 UTC, hideo54 approved these changes
OK

2021-11-22 11:29 UTC, hideo54 commented on views/contest.pug
> -    if contest.id === '1'
これやったの博多市でした ずび

2021-11-22 11:30 UTC, hideo54 commented
一旦これで merge します。ありがとうございました〜!

2021-11-22 11:31 UTC, merged

2021-11-22 11:40 UTC, hideo54 commented on views/contest.pug
> -    if contest.id === '1'
これマジで最悪で、きつねが conflict 解消作業の際に古い方を採用してしまった挙げ句それを昆布くんのせいだと勘違いして詰めてしまいました 撃たれるべき ずび

2021-11-22 12:02 UTC, kom-bu commented on views/contest.pug
> -    if contest.id === '1'
:i-e: